### ISSUE TITLE
yield inside tokio select! doesn't work

### ISSUE THREAD

**Issue by tekjar** [tokio-rs/async-stream#27]
Yielding [here](https://github.com/tekjar/rumq/blob/master/rumq-client/src/eventloop.rs#L123) inside tokio `select!` doesn't work. I can bypass the error with a variable but I'm facing a compiler crash with assignments like this
```
exit = Notification::StreamEnd(e.into());
```
So I'm mixing yields and assignments to make the code compile.

As the description says, yielding inside `select!` will be helpful for my use case :)

**Comment by carllerche** [comment]
What error? My guess is that `async-stream` doesn't try to parse macros... we might want to special case a few "known" ones.

**Comment by polachok** [comment]
```
  --> src/main.rs:15:17
   |
15 |                 yield x;
   |                 ^^^^^^^
   |
   = note: see issue #43122 <https://github.com/rust-lang/rust/issues/43122> for more information
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
```

```
use futures::select;
use futures::future::FutureExt;

async fn five() -> u32 {
    5
}

async fn f() {
    let x = five().fuse();
    tokio::pin!(x);

    async_stream::try_stream! {
        select! {
            x = x => {
                yield x;
            }
        }
    };
}

fn main() {
}
```

**Comment by LucioFranco** [comment]
This seems like we may want to try to parse out tokio's select here?

**Comment by SergioBenitez** [comment]
I just hit this issue which wholly prevented my intended use for the crate.

Without looking at the source, I suspect that the implementation:

  1. Parses the internal tokens as series of `stmt`s.
  2. Visit the `stmt`s, rewriting `yield` expressions.

Because a macro invocation's token stream is parsed as a series of tokens inside of the top-level `expr`, a `yield` expression inside of a macro invocation is _not_ a `yield` expression, and thus is ignored by this strategy. I'd like to suggest a different strategy:

  1. Scan for `yield` tokens.
  2. Parse the stream beginning at the next token as an `expr`.
  3. Rewrite the `yield` + `expr` as before.

Not only does this approach resolve this issue, it also parses only what it needs and will work with _any_ internal macro invocation.
