### ISSUE TITLE
async_stream_impl 0.3.1 removes stream, try_stream, breaking async_stream =0.3.0

### ISSUE THREAD

**Issue by dfreese** [tokio-rs/async-stream#58]
I had async_stream pinned to "=0.3.0", and as a result, ran into the following error:
```
error[E0432]: unresolved imports `async_stream_impl::stream`, `async_stream_impl::try_stream`
   --> external/raze__async_stream__0_3_0/src/lib.rs:171:29
    |
171 | pub use async_stream_impl::{stream, try_stream};
    |                             ^^^^^^  ^^^^^^^^^^ no `try_stream` in the root
    |                             |
    |                             no `stream` in the root

error: aborting due to previous error
```
We try to pin our main dependencies, to keep a little more control over how things update.  Updating to 0.3.1 for async stream 0.3.1 isn't a problem, but should 0.3.1 have been 0.4?

**Comment by taiki-e** [comment]
async_stream_impl is Implementation detail of the `async_stream` crate. Most crates do not support updating only implementation details.

However, this issue has been fixed in 0.3.1 (https://github.com/tokio-rs/async-stream/pull/52#discussion_r560827226) and should not occur in future versions.

> We try to pin our main dependencies, to keep a little more control over how things update. Updating to 0.3.1 for async stream 0.3.1 isn't a problem, but should 0.3.1 have been 0.4?

I recommend using [Cargo.lock](https://doc.rust-lang.org/cargo/guide/cargo-toml-vs-cargo-lock.html) for this purpose. Doing this using Cargo.toml is not intended and usually does not work.
