### ISSUE TITLE
Return a stream conditionally

### ISSUE THREAD

**Issue by Soremwar** [tokio-rs/async-stream#88]
```rs
fn a() -> impl Stream<Item = Result<u8, ()>> {
    try_stream!{
        yield 1;
    }
}

fn b() -> impl Stream<Item = Result<u8, ()>> {
    try_stream!{
        yield 2;
    }
}

fn decide(a: bool) -> impl Stream<Item = Result<u8, ()>> {
    if true {
        a()
    } else {
        b()
    }
}

fn main(){
    decide(false);
}
```

Will complain that `a` and `b` have incompatible types: `distinct uses of "impl Trait" result in different opaque types`

Boxing them will make me unable to pin them going forward, so what should be the way forward here?

**Comment by taiki-e** [comment]
The streams returned by stream!/try_stream contain opaque types (impl trait), so they are treated as different types even if the signatures are the same.

There are a few ways to handle such cases:
- Boxing. However, when boxing futures, streams, etc., you need to use Box::pin instead of Box::new.
- Enum. e.g., you can use [Either type from futures/futures-util](https://docs.rs/futures/latest/futures/future/enum.Either.html)
- Macro/feature to automate patterns that use enum. e.g., [auto_enums crate](https://github.com/taiki-e/auto_enums), [RFC 3367](https://github.com/rust-lang/rfcs/pull/3367)
